



export const DELETE_ATTENDANCE_REQUEST='DELETE_ATTENDANCE_REQUEST'
export const DELETE_ATTENDANCE_SUCCESS='DELETE_ATTENDANCE_SUCCESS'
export const DELETE_ATTENDANCE_FAIL='DELETE_ATTENDANCE_FAIL'

export const ATTENDANCE_LIST_REQUEST='ATTENDANCE_LIST_REQUEST'
export const ATTENDANCE_LIST_SUCCESS='ATTENDANCE_LIST_SUCCESS'
export const ATTENDANCE_LIST_FAIL='ATTENDANCE_LIST_FAIL'


