export const ADD_FEE_REQUEST='ADD_FEE_REQUEST'
export const ADD_FEE_SUCCESS='ADD_FEE_SUCCESS'
export const ADD_FEE_FAIL='ADD_FEE_FAIL'

export const UPDATE_FEE_REQUEST='UPDATE_FEE_REQUEST'
export const UPDATE_FEE_SUCCESS='UPDATE_FEE_SUCCESS'
export const UPDATE_FEE_FAIL='UPDATE_FEE_FAIL'

export const DELETE_FEE_REQUEST='DELETE_FEE_REQUEST'
export const DELETE_FEE_SUCCESS='DELETE_FEE_SUCCESS'
export const DELETE_FEE_FAIL='DELETE_FEE_FAIL'

export const FEE_LIST_REQUEST='FEE_LIST_REQUEST'
export const FEE_LIST_SUCCESS='FEE_LIST_SUCCESS'
export const FEE_LIST_FAIL='FEE_LIST_FAIL'

export const FEE_DETAILS_REQUEST='FEE_DETAILS_REQUEST'
export const FEE_DETAILS_SUCCESS='FEE_DETAILS_SUCCESS'
export const FEE_DETAILS_FAIL='FEE_DETAILS_FAIL'

export const FEE_COUNT_REQUEST='FEE_COUNT_REQUEST'
export const FEE_COUNT_SUCCESS='FEE_COUNT_SUCCESS'
export const FEE_COUNT_FAIL='FEE_COUNT_FAIL'

export const FEE_TRAINING_REQUEST='FEE_TRAINING_REQUEST'
export const FEE_TRAINING_SUCCESS='FEE_TRAINING_SUCCESS'
export const FEE_TRAINING_FAIL='FEE_TRAINING_FAIL'

export const FEE_CARDIO_REQUEST='FEE_CARDIO_REQUEST'
export const FEE_CARDIO_SUCCESS='FEE_CARDIO_SUCCESS'
export const FEE_CARDIO_FAIL='FEE_CARDIO_FAIL'

export const FEE_WEIGHT_REQUEST='FEE_WEIGHT_REQUEST'
export const FEE_WEIGHT_SUCCESS='FEE_WEIGHT_SUCCESS'
export const FEE_WEIGHT_FAIL='FEE_WEIGHT_FAIL'



