export const ADD_MEMBER_REQUEST='ADD_MEMBER_REQUEST'
export const ADD_MEMBER_SUCCESS='ADD_MEMBER_SUCCESS'
export const ADD_MEMBER_FAIL='ADD_MEMBER_FAIL'

export const UPDATE_MEMBER_REQUEST='UPDATE_MEMBER_REQUEST'
export const UPDATE_MEMBER_SUCCESS='UPDATE_MEMBER_SUCCESS'
export const UPDATE_MEMBER_FAIL='UPDATE_MEMBER_FAIL'

export const DELETE_MEMBER_REQUEST='DELETE_MEMBER_REQUEST'
export const DELETE_MEMBER_SUCCESS='DELETE_MEMBER_SUCCESS'
export const DELETE_MEMBER_FAIL='DELETE_MEMBER_FAIL'

export const MEMBER_LIST_REQUEST='MEMBER_LIST_REQUEST'
export const MEMBER_LIST_SUCCESS='MEMBER_LIST_SUCCESS'
export const MEMBER_LIST_FAIL='MEMBER_LIST_FAIL'

export const MEMBER_DETAILS_REQUEST='MEMBER_DETAILS_REQUEST'
export const MEMBER_DETAILS_SUCCESS='MEMBER_DETAILS_SUCCESS'
export const MEMBER_DETAILS_FAIL='MEMBER_DETAILS_FAIL'

export const MEMBER_COUNT_REQUEST='MEMBER_COUNT_REQUEST'
export const MEMBER_COUNT_SUCCESS='MEMBER_COUNT_SUCCESS'
export const MEMBER_COUNT_FAIL='MEMBER_COUNT_FAIL'
