export const ADD_MEMBER_REQUEST='ADD_MEMBER_REQUEST'
export const ADD_MEMBER_SUCCESS='ADD_MEMBER_SUCCESS'
export const ADD_MEMBER_FAIL='ADD_MEMBER_FAIL'

export const UPDATE_MEMBER_REQUEST='UPDATE_MEMBER_REQUEST'
export const UPDATE_MEMBER_SUCCESS='UPDATE_MEMBER_SUCCESS'
export const UPDATE_MEMBER_FAIL='UPDATE_MEMBER_FAIL'

export const DELETE_MEMBER_REQUEST='DELETE_MEMBER_REQUEST'
export const DELETE_MEMBER_SUCCESS='DELETE_MEMBER_SUCCESS'
export const DELETE_MEMBER_FAIL='DELETE_MEMBER_FAIL'

export const MEMBER_LIST_REQUEST='MEMBER_LIST_REQUEST'
export const MEMBER_LIST_SUCCESS='MEMBER_LIST_SUCCESS'
export const MEMBER_LIST_FAIL='MEMBER_LIST_FAIL'

export const MEMBER_DETAILS_REQUEST='MEMBER_DETAILS_REQUEST'
export const MEMBER_DETAILS_SUCCESS='MEMBER_DETAILS_SUCCESS'
export const MEMBER_DETAILS_FAIL='MEMBER_DETAILS_FAIL'

export const MEMBER_COUNT_REQUEST='MEMBER_COUNT_REQUEST'
export const MEMBER_COUNT_SUCCESS='MEMBER_COUNT_SUCCESS'
export const MEMBER_COUNT_FAIL='MEMBER_COUNT_FAIL'

export const MEMBER_TRAINING_REQUEST='MEMBER_TRAINING_REQUEST'
export const MEMBER_TRAINING_SUCCESS='MEMBER_TRAINING_SUCCESS'
export const MEMBER_TRAINING_FAIL='MEMBER_TRAINING_FAIL'

export const MEMBER_CARDIO_REQUEST='MEMBER_CARDIO_REQUEST'
export const MEMBER_CARDIO_SUCCESS='MEMBER_CARDIO_SUCCESS'
export const MEMBER_CARDIO_FAIL='MEMBER_CARDIO_FAIL'

export const MEMBER_WEIGHT_REQUEST='MEMBER_WEIGHT_REQUEST'
export const MEMBER_WEIGHT_SUCCESS='MEMBER_WEIGHT_SUCCESS'
export const MEMBER_WEIGHT_FAIL='MEMBER_WEIGHT_FAIL'

export const MEMBER_CARDIOWEIGHT_REQUEST='MEMBER_CARDIOWEIGHT_REQUEST'
export const MEMBER_CARDIOWEIGHT_SUCCESS='MEMBER_CARDIOWEIGHT_SUCCESS'
export const MEMBER_CARDIOWEIGHT_FAIL='MEMBER_CARDIOWEIGHT_FAIL'

export const ALLMEMBERS_LIST_REQUEST='ALLMEMBERS_LIST_REQUEST'
export const ALLMEMBERS_LIST_SUCCESS='ALLMEMBERS_LIST_SUCCESS'
export const ALLMEMBERS_LIST_FAIL='ALLMEMBERS_LIST_FAIL'

