export const ADD_RFID_REQUEST='ADD_RFID_REQUEST'
export const ADD_RFID_SUCCESS='ADD_RFID_SUCCESS'
export const ADD_RFID_FAIL='ADD_RFID_FAIL'

export const VERIFY_RFID_REQUEST='VERIFY_RFID_REQUEST'
export const VERIFY_RFID_SUCCESS='VERIFY_RFID_SUCCESS'
export const VERIFY_RFID_FAIL='VERIFY_RFID_FAIL'


