export const ADD_STAFF_REQUEST='ADD_STAFF_REQUEST'
export const ADD_STAFF_SUCCESS='ADD_STAFF_SUCCESS'
export const ADD_STAFF_FAIL='ADD_STAFF_FAIL'

export const UPDATE_STAFF_REQUEST='UPDATE_STAFF_REQUEST'
export const UPDATE_STAFF_SUCCESS='UPDATE_STAFF_SUCCESS'
export const UPDATE_STAFF_FAIL='UPDATE_STAFF_FAIL'

export const DELETE_STAFF_REQUEST='DELETE_STAFF_REQUEST'
export const DELETE_STAFF_SUCCESS='DELETE_STAFF_SUCCESS'
export const DELETE_STAFF_FAIL='DELETE_STAFF_FAIL'

export const STAFF_LIST_REQUEST='STAFF_LIST_REQUEST'
export const STAFF_LIST_SUCCESS='STAFF_LIST_SUCCESS'
export const STAFF_LIST_FAIL='STAFF_LIST_FAIL'

export const STAFF_DETAILS_REQUEST='STAFF_DETAILS_REQUEST'
export const STAFF_DETAILS_SUCCESS='STAFF_DETAILS_SUCCESS'
export const STAFF_DETAILS_FAIL='STAFF_DETAILS_FAIL'

export const STAFF_COUNT_REQUEST='STAFF_COUNT_REQUEST'
export const STAFF_COUNT_SUCCESS='STAFF_COUNT_SUCCESS'
export const STAFF_COUNT_FAIL='STAFF_COUNT_FAIL'
